# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_posted_by'),
        ('posts', '0002_tag'),
    ]

    operations = [
    ]
