# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_share'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='share',
            name='shared_by',
        ),
        migrations.AddField(
            model_name='share',
            name='shared_post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='posts.Post'),
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='posts.Post'),
        ),
    ]
