# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20160916_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='shared_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='posts.Post'),
        ),
    ]
