# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-19 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20160916_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='original_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original', to='posts.Post'),
        ),
        migrations.AlterField(
            model_name='share',
            name='shared_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
        ),
    ]
