# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20160919_1447'),
        ('posts', '0008_auto_20160917_1436'),
    ]

    operations = [
    ]
