# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 14:52
from __future__ import unicode_literals

from django.db import migrations
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
                ('objects', profiles.models.MyUserManager()),
            ],
        ),
    ]
