# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-26 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_auto_20160920_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='recipient_seen',
            field=models.BooleanField(default=False),
        ),
    ]
